SELECT a.ID, 
(
    CASE 
        WHEN b.CHILD_COUNT IS NULL THEN 0
        ELSE b.CHILD_COUNT
    END
) CHILD_COUNT
FROM ECOLI_DATA a
LEFT OUTER JOIN
(
    SELECT PARENT_ID, COUNT(1) CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
) b
ON a.ID=b.PARENT_ID