SELECT 
    YEAR(a.DIFFERENTIATION_DATE) YEAR, 
    b.MAX_SIZE-a.SIZE_OF_COLONY YEAR_DEV, 
    ID
FROM ECOLI_DATA a
JOIN
(
    SELECT MAX(SIZE_OF_COLONY) MAX_SIZE, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
) b
ON YEAR(a.DIFFERENTIATION_DATE)=b.YEAR
ORDER BY YEAR, YEAR_DEV