SELECT a.ID, b.FISH_NAME, b.LENGTH
FROM FISH_INFO a
JOIN
(
    SELECT fi.FISH_TYPE, fni.FISH_NAME, MAX(fi.LENGTH) LENGTH
    FROM FISH_INFO fi
    JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE=fni.FISH_TYPE
    GROUP BY fi.FISH_TYPE, fni.FISH_NAME
) b
ON a.FISH_TYPE=b.FISH_TYPE AND a.LENGTH=b.LENGTH
